[2025-05-15T05:09:57.477+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:06:31.356105+00:00 [queued]>
[2025-05-15T05:09:57.498+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:06:31.356105+00:00 [queued]>
[2025-05-15T05:09:57.499+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-05-15T05:09:57.534+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-15 05:06:31.356105+00:00
[2025-05-15T05:09:57.541+0000] {standard_task_runner.py:60} INFO - Started process 3496 to run task
[2025-05-15T05:09:57.546+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'manual__2025-05-15T05:06:31.356105+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmp2h_x_7df']
[2025-05-15T05:09:57.550+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask fetch_and_store_weather
[2025-05-15T05:09:57.593+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T05:09:57.631+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T05:06:31.356105+00:00 [running]> on host 80d173fc4dec
[2025-05-15T05:09:57.752+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T05:06:31.356105+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T05:06:31.356105+00:00'
[2025-05-15T05:09:57.840+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T05:10:01.604+0000] {logging_mixin.py:188} INFO - Error inserting weather data: could not translate host name "postgres" to address: Name or service not known
[2025-05-15T05:10:01.605+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/db_writer.py", line 55, in insert_weather_data
    conn = get_db_connection()
  File "/opt/airflow/dags/db_writer.py", line 16, in get_db_connection
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/daily_weather_dag.py", line 15, in fetch_and_store
    insert_weather_data(data)
  File "/opt/airflow/dags/db_writer.py", line 81, in insert_weather_data
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment
[2025-05-15T05:10:01.619+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250515T050631, start_date=20250515T050957, end_date=20250515T051001
[2025-05-15T05:10:01.652+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task fetch_and_store_weather (local variable 'conn' referenced before assignment; 3496)
[2025-05-15T05:10:01.670+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T05:10:01.684+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
