[2025-05-15T04:46:46.464+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T04:46:46.490+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T04:46:46.491+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T04:46:46.563+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-14 00:00:00+00:00
[2025-05-15T04:46:46.577+0000] {standard_task_runner.py:60} INFO - Started process 1565 to run task
[2025-05-15T04:46:46.589+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmpyqtqzot7']
[2025-05-15T04:46:46.595+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask fetch_and_store_weather
[2025-05-15T04:46:46.651+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T04:46:46.751+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [running]> on host 80d173fc4dec
[2025-05-15T04:46:46.957+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T00:00:00+00:00'
[2025-05-15T04:46:47.092+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T04:46:50.869+0000] {logging_mixin.py:188} INFO - Error inserting weather data: could not translate host name "postgres" to address: Name or service not known
[2025-05-15T04:46:50.873+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/db_writer.py", line 55, in insert_weather_data
    conn = get_db_connection()
  File "/opt/airflow/dags/db_writer.py", line 16, in get_db_connection
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/daily_weather_dag.py", line 15, in fetch_and_store
    insert_weather_data(data)
  File "/opt/airflow/dags/db_writer.py", line 81, in insert_weather_data
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment
[2025-05-15T04:46:50.938+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250514T000000, start_date=20250515T044646, end_date=20250515T044650
[2025-05-15T04:46:51.048+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task fetch_and_store_weather (local variable 'conn' referenced before assignment; 1565)
[2025-05-15T04:46:51.086+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T04:46:51.118+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T05:20:50.948+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T05:20:50.959+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T05:20:50.960+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T05:20:50.987+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-14 00:00:00+00:00
[2025-05-15T05:20:50.997+0000] {standard_task_runner.py:60} INFO - Started process 306 to run task
[2025-05-15T05:20:51.006+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmplja7nbvh']
[2025-05-15T05:20:51.011+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask fetch_and_store_weather
[2025-05-15T05:20:51.048+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T05:20:51.094+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [running]> on host 2158c1e84d48
[2025-05-15T05:20:51.188+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T00:00:00+00:00'
[2025-05-15T05:20:51.294+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T05:20:55.058+0000] {logging_mixin.py:188} INFO - Error inserting weather data: could not translate host name "postgres" to address: Name or service not known
[2025-05-15T05:20:55.061+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/db_writer.py", line 55, in insert_weather_data
    conn = get_db_connection()
  File "/opt/airflow/dags/db_writer.py", line 16, in get_db_connection
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/daily_weather_dag.py", line 15, in fetch_and_store
    insert_weather_data(data)
  File "/opt/airflow/dags/db_writer.py", line 81, in insert_weather_data
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment
[2025-05-15T05:20:55.089+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250514T000000, start_date=20250515T052050, end_date=20250515T052055
[2025-05-15T05:20:55.124+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task fetch_and_store_weather (local variable 'conn' referenced before assignment; 306)
[2025-05-15T05:20:55.139+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T05:20:55.152+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T05:39:38.937+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T05:39:38.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T05:39:38.976+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T05:39:39.039+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-14 00:00:00+00:00
[2025-05-15T05:39:39.049+0000] {standard_task_runner.py:60} INFO - Started process 212 to run task
[2025-05-15T05:39:39.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmpjctr2xg5']
[2025-05-15T05:39:39.070+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask fetch_and_store_weather
[2025-05-15T05:39:39.119+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T05:39:39.197+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [running]> on host d34e993fee47
[2025-05-15T05:39:39.319+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T00:00:00+00:00'
[2025-05-15T05:39:42.503+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T05:39:46.324+0000] {logging_mixin.py:188} INFO - Error inserting data: 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
[2025-05-15T05:39:46.325+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-15T05:39:46.336+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250514T000000, start_date=20250515T053938, end_date=20250515T053946
[2025-05-15T05:39:46.378+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T05:39:46.399+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T10:21:49.562+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T10:21:49.582+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T10:21:49.583+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T10:21:49.621+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-14 00:00:00+00:00
[2025-05-15T10:21:49.628+0000] {standard_task_runner.py:60} INFO - Started process 1813 to run task
[2025-05-15T10:21:49.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmprxr7_tx0']
[2025-05-15T10:21:49.666+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask fetch_and_store_weather
[2025-05-15T10:21:49.777+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T10:21:49.884+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [running]> on host 4a83c4b3f003
[2025-05-15T10:21:50.104+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T00:00:00+00:00'
[2025-05-15T10:21:50.194+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T10:21:50.292+0000] {logging_mixin.py:188} INFO - Error inserting data: 1049 (42000): Unknown database 'weatherdata'
[2025-05-15T10:21:50.293+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-15T10:21:50.309+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250514T000000, start_date=20250515T102149, end_date=20250515T102150
[2025-05-15T10:21:50.379+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T10:21:50.395+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T11:47:16.677+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T11:47:16.698+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T11:47:16.699+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T11:47:16.740+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-14 00:00:00+00:00
[2025-05-15T11:47:16.746+0000] {standard_task_runner.py:60} INFO - Started process 328 to run task
[2025-05-15T11:47:16.754+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmp1fafa0bg']
[2025-05-15T11:47:16.759+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask fetch_and_store_weather
[2025-05-15T11:47:16.806+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T11:47:16.889+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather scheduled__2025-05-14T00:00:00+00:00 [running]> on host 6648ba4bf9c3
[2025-05-15T11:47:17.107+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T00:00:00+00:00'
[2025-05-15T11:47:17.284+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T11:47:17.466+0000] {logging_mixin.py:188} INFO - Successfully inserted weather data for Hyderabad
[2025-05-15T11:47:17.469+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-15T11:47:17.497+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250514T000000, start_date=20250515T114716, end_date=20250515T114717
[2025-05-15T11:47:17.571+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T11:47:17.633+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
